-- =============================================================================
-- Ticketing Mundial 2026 — Esquema (DDL)
-- PostgreSQL. Identificadores en snake_case (Postgres pliega a minúsculas).
-- Generado a partir del pasaje a tablas (sección 9 del prompt). FUENTE DE VERDAD.
-- Revisar y completar: es una versión inicial del equipo.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Catálogos / tablas simples
-- ---------------------------------------------------------------------------
CREATE TABLE comision (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    porcentaje  NUMERIC(5, 2) NOT NULL
);

CREATE TABLE estado_venta (
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE estado_identidad (
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE equipo (
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

CREATE TABLE sede (
    nombre VARCHAR(100) PRIMARY KEY
);

-- ---------------------------------------------------------------------------
-- Usuarios y jerarquía ISA (Funcionario / Administrador)
-- ---------------------------------------------------------------------------
CREATE TABLE usuario (
    numero_documento VARCHAR(30) PRIMARY KEY,
    mail             VARCHAR(150) NOT NULL,
    pais             VARCHAR(100),
    localidad        VARCHAR(100),
    calle            VARCHAR(150),
    numero_direccion VARCHAR(20),
    codigo_postal    VARCHAR(20),
    fecha_registro   TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE documento (
    usuario_numero_documento VARCHAR(30) NOT NULL REFERENCES usuario (numero_documento),
    tipo                     VARCHAR(50) NOT NULL,
    pais                     VARCHAR(100),
    PRIMARY KEY (usuario_numero_documento, tipo)
);

CREATE TABLE telefono (
    usuario_numero_documento VARCHAR(30) NOT NULL REFERENCES usuario (numero_documento),
    telefono                 VARCHAR(30) NOT NULL,
    PRIMARY KEY (usuario_numero_documento, telefono)
);

CREATE TABLE tiene_estado_identidad (
    usuario_numero_documento VARCHAR(30) NOT NULL REFERENCES usuario (numero_documento),
    id_estado_identidad      INT NOT NULL REFERENCES estado_identidad (id),
    PRIMARY KEY (usuario_numero_documento, id_estado_identidad)
);

CREATE TABLE funcionario (
    numero_documento VARCHAR(30) PRIMARY KEY REFERENCES usuario (numero_documento),
    numero_legajo    VARCHAR(30) NOT NULL
);

CREATE TABLE dispositivo_autorizado (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(100) NOT NULL,
    numero_documento VARCHAR(30) NOT NULL REFERENCES funcionario (numero_documento)
);

CREATE TABLE administrador (
    numero_documento VARCHAR(30) PRIMARY KEY REFERENCES usuario (numero_documento),
    fecha_asignacion TIMESTAMP NOT NULL DEFAULT now(),
    nombre_sede      VARCHAR(100) NOT NULL REFERENCES sede (nombre)
);

-- ---------------------------------------------------------------------------
-- Infraestructura: estadios y sectores
-- ---------------------------------------------------------------------------
CREATE TABLE estadio (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_sede      VARCHAR(100) NOT NULL REFERENCES sede (nombre),
    capacidad_maxima INT NOT NULL,
    ubicacion        VARCHAR(200)
);

CREATE TABLE sector (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estadio INT NOT NULL REFERENCES estadio (id),
    nombre     VARCHAR(100) NOT NULL,
    capacidad  INT NOT NULL
);

-- ---------------------------------------------------------------------------
-- Eventos deportivos
-- NOTA: el id NO venía en el pasaje original; se AGREGA como PK (lo referencian FKs).
-- ---------------------------------------------------------------------------
CREATE TABLE evento_deportivo (
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipo_local      INT NOT NULL REFERENCES equipo (id),
    id_equipo_visitante  INT NOT NULL REFERENCES equipo (id),
    fecha                DATE NOT NULL,
    hora                 TIME NOT NULL,
    cantidad_entradas    INT NOT NULL
);

-- Sectores habilitados por evento (PK compuesta sector + evento).
CREATE TABLE informacion_entrada (
    id_sector                      INT NOT NULL REFERENCES sector (id),
    id_evento_deportivo            INT NOT NULL REFERENCES evento_deportivo (id),
    numero_documento_administrador VARCHAR(30) NOT NULL REFERENCES administrador (numero_documento),
    PRIMARY KEY (id_sector, id_evento_deportivo)
);

-- ---------------------------------------------------------------------------
-- Ventas y entradas
-- ---------------------------------------------------------------------------
CREATE TABLE venta (
    id                       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_documento_usuario VARCHAR(30) NOT NULL REFERENCES usuario (numero_documento),
    id_comision              INT NOT NULL REFERENCES comision (id),
    fecha                    TIMESTAMP NOT NULL DEFAULT now(),
    monto_total              NUMERIC(12, 2) NOT NULL
);

CREATE TABLE venta_tiene_estado (
    id_venta        INT NOT NULL REFERENCES venta (id),
    id_estado_venta INT NOT NULL REFERENCES estado_venta (id),
    PRIMARY KEY (id_venta, id_estado_venta)
);

CREATE TABLE entrada (
    id                             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado                         VARCHAR(50) NOT NULL,
    fecha                          TIMESTAMP NOT NULL DEFAULT now(),
    estado_seed                    VARCHAR(100),
    qr_usado                       BOOLEAN NOT NULL DEFAULT FALSE,
    costo                          NUMERIC(12, 2) NOT NULL,
    id_sector                      INT NOT NULL REFERENCES sector (id),
    id_evento_deportivo            INT NOT NULL REFERENCES evento_deportivo (id),
    numero_documento_administrador VARCHAR(30) REFERENCES administrador (numero_documento),
    id_venta                       INT NOT NULL REFERENCES venta (id)
    -- FK compuesta opcional al sector habilitado del evento:
    -- , FOREIGN KEY (id_sector, id_evento_deportivo)
    --       REFERENCES informacion_entrada (id_sector, id_evento_deportivo)
);

CREATE TABLE transferencia (
    numero_documento_emisor   VARCHAR(30) NOT NULL REFERENCES usuario (numero_documento),
    numero_documento_receptor VARCHAR(30) NOT NULL REFERENCES usuario (numero_documento),
    id_entrada                INT NOT NULL REFERENCES entrada (id),
    fecha                     TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY (numero_documento_emisor, numero_documento_receptor, id_entrada)
);

-- =============================================================================
-- HUECOS CONOCIDOS respecto a la letra (NO resolver inventando tablas acá;
-- discutir con el equipo y completar el pasaje a tablas).
-- -----------------------------------------------------------------------------
--  1) Entrada no tiene DUEÑO ACTUAL (relación EsDueño). Las transferencias no
--     pueden cambiar de propietario sin una columna tipo:
--        ALTER TABLE entrada ADD COLUMN numero_documento_duenio_actual
--            VARCHAR(30) REFERENCES usuario (numero_documento);
--
--  2) No existe entidad de VALIDACIÓN/ACCESO (funcionario validador + código QR
--     aceptado + dispositivo + marca "consumida"), ni histórico de QR. Ej.:
--        CREATE TABLE validacion_acceso (
--            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--            id_entrada INT REFERENCES entrada (id),
--            numero_documento_funcionario VARCHAR(30) REFERENCES funcionario (numero_documento),
--            id_dispositivo INT REFERENCES dispositivo_autorizado (id),
--            codigo_qr VARCHAR(200), aceptado BOOLEAN, fecha TIMESTAMP);
--
--  3) No hay vínculo directo EVENTO_DEPORTIVO -> ESTADIO. Ej.:
--        ALTER TABLE evento_deportivo ADD COLUMN id_estadio INT REFERENCES estadio (id);
--
--  4) No existe el RBAC DINÁMICO (rol, permiso, rol_permiso, usuario_rol,
--     log_usuario) de la lista de funcionalidades; solo la jerarquía ISA fija.
-- =============================================================================
